<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="bin\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryManagement.Application\InventoryManagement.Application.csproj" />
    <ProjectReference Include="..\InventoryManagement.Domain\InventoryManagement.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.19">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.19">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authentication\" />
    <Folder Include="Caching\" />
    <Folder Include="Data\Migrations\" />
    <Folder Include="Email\" />
    <Folder Include="FileStorage\" />
    <Folder Include="Interfaces\Repositories\" />
    <Folder Include="Reporting\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
